<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'oc_platform.doctrine_listener.application_creation' shared autowired service.

return $this->services['oc_platform.doctrine_listener.application_creation'] = new \OC\PlatformBundle\DoctrineListener\ApplicationCreationListener(${($_ = isset($this->services['oc_platform.email.application_mailer']) ? $this->services['oc_platform.email.application_mailer'] : $this->load(__DIR__.'/getOcPlatform_Email_ApplicationMailerService.php')) && false ?: '_'});
