<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerC69pruo\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerC69pruo/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerC69pruo.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerC69pruo\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerC69pruo\appDevDebugProjectContainer();
